/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ussr_samples_odin_natives_OdinNativeTinyOSController */

#ifndef _Included_ussr_samples_odin_natives_OdinNativeTinyOSController
#define _Included_ussr_samples_odin_natives_OdinNativeTinyOSController
#ifdef __cplusplus
extern "C" {
#endif
#undef ussr_samples_odin_natives_OdinNativeTinyOSController_sleepThreshold
#define ussr_samples_odin_natives_OdinNativeTinyOSController_sleepThreshold 100L
/*
 * Class:     ussr_samples_odin_natives_OdinNativeTinyOSController
 * Method:    nativeSendDone
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_ussr_samples_odin_natives_OdinNativeTinyOSController_nativeSendDone
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     ussr_samples_odin_natives_OdinNativeTinyOSController
 * Method:    nativeHandleMessage
 * Signature: (I[BII)V
 */
JNIEXPORT void JNICALL Java_ussr_samples_odin_natives_OdinNativeTinyOSController_nativeHandleMessage
  (JNIEnv *, jobject, jint, jbyteArray, jint, jint);

/*
 * Class:     ussr_samples_odin_natives_OdinNativeTinyOSController
 * Method:    nativeMillisecondElapsed
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_ussr_samples_odin_natives_OdinNativeTinyOSController_nativeMillisecondElapsed
  (JNIEnv *, jobject, jint);

/*
 * Class:     ussr_samples_odin_natives_OdinNativeTinyOSController
 * Method:    native_stub
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_ussr_samples_odin_natives_OdinNativeTinyOSController_native_1stub
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class ussr_samples_odin_natives_OdinNativeTinyOSController_Link */

#ifndef _Included_ussr_samples_odin_natives_OdinNativeTinyOSController_Link
#define _Included_ussr_samples_odin_natives_OdinNativeTinyOSController_Link
#ifdef __cplusplus
extern "C" {
#endif
#undef ussr_samples_odin_natives_OdinNativeTinyOSController_Link_MODULE_TYPE_UNKNOWN
#define ussr_samples_odin_natives_OdinNativeTinyOSController_Link_MODULE_TYPE_UNKNOWN 0L
#undef ussr_samples_odin_natives_OdinNativeTinyOSController_Link_MODULE_TYPE_ODIN_BALL
#define ussr_samples_odin_natives_OdinNativeTinyOSController_Link_MODULE_TYPE_ODIN_BALL 1L
#undef ussr_samples_odin_natives_OdinNativeTinyOSController_Link_MODULE_TYPE_SSR_LINEAR_ACTUATOR
#define ussr_samples_odin_natives_OdinNativeTinyOSController_Link_MODULE_TYPE_SSR_LINEAR_ACTUATOR 2L
#ifdef __cplusplus
}
#endif
#endif
