/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ussr_samples_atron_natives_ATRONNativeTinyOSController */

#ifndef _Included_ussr_samples_atron_natives_ATRONNativeTinyOSController
#define _Included_ussr_samples_atron_natives_ATRONNativeTinyOSController
#ifdef __cplusplus
extern "C" {
#endif
#undef ussr_samples_atron_natives_ATRONNativeTinyOSController_sleepThreshold
#define ussr_samples_atron_natives_ATRONNativeTinyOSController_sleepThreshold 100L
/*
 * Class:     ussr_samples_atron_natives_ATRONNativeTinyOSController
 * Method:    nativeSendDone
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_ussr_samples_atron_natives_ATRONNativeTinyOSController_nativeSendDone
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     ussr_samples_atron_natives_ATRONNativeTinyOSController
 * Method:    nativeHandleMessage
 * Signature: (I[BII)V
 */
JNIEXPORT void JNICALL Java_ussr_samples_atron_natives_ATRONNativeTinyOSController_nativeHandleMessage
  (JNIEnv *, jobject, jint, jbyteArray, jint, jint);

/*
 * Class:     ussr_samples_atron_natives_ATRONNativeTinyOSController
 * Method:    nativeMillisecondElapsed
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_ussr_samples_atron_natives_ATRONNativeTinyOSController_nativeMillisecondElapsed
  (JNIEnv *, jobject, jint);

/*
 * Class:     ussr_samples_atron_natives_ATRONNativeTinyOSController
 * Method:    native_stub
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_ussr_samples_atron_natives_ATRONNativeTinyOSController_native_1stub
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class ussr_samples_atron_natives_ATRONNativeTinyOSController_Link */

#ifndef _Included_ussr_samples_atron_natives_ATRONNativeTinyOSController_Link
#define _Included_ussr_samples_atron_natives_ATRONNativeTinyOSController_Link
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
