/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ussr_samples_atron_natives_ATRONNativeTinyOSController */

#ifndef _Included_ussr_samples_atron_natives_ATRONNativeTinyOSController
#define _Included_ussr_samples_atron_natives_ATRONNativeTinyOSController
#ifdef __cplusplus
extern "C" {
#endif
#undef ussr_samples_atron_natives_ATRONNativeTinyOSController_sleepThreshold
#define ussr_samples_atron_natives_ATRONNativeTinyOSController_sleepThreshold 100L
/*
 * Class:     ussr_samples_atron_natives_ATRONNativeTinyOSController
 * Method:    nativeSendDone
 * Signature: ([BI)V
 */
JNIEXPORT void JNICALL Java_ussr_samples_atron_natives_ATRONNativeTinyOSController_nativeSendDone
  (JNIEnv *, jobject, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class ussr_samples_atron_natives_ATRONNativeTinyOSController_Link */

#ifndef _Included_ussr_samples_atron_natives_ATRONNativeTinyOSController_Link
#define _Included_ussr_samples_atron_natives_ATRONNativeTinyOSController_Link
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
