package ussr.physics;

/**
* Utility class allowing the physics-engine specific representation of a vector
* generated by the physics engine to be stored at the abstract model level of the
* software.  Can in principle store any kind of object, but should only be used to
* store vectors from the physics engine.
* 
* @author Modular Robots @ MMMI
*
*/
public class PhysicsVectorHolder {
    /**
     * The vector being held 
     */
    private Object physicsVector;
    /**
     * Create a physics engine independent vector holder
     * @param physicsVector the vector to hold
     */
    public PhysicsVectorHolder(Object physicsVector) {
        this.physicsVector = physicsVector;
    }
    /**
     * Get the physics engine specific vector stored in this holder
     * @return the vector being held
     */
    public Object get() { return physicsVector; }
}
