package ussr.physics;

/**
 * Utility class allowing the physics-engine specific representation of a quaternion
 * generated by the physics engine to be stored at the abstract model level of the
 * software.  Can in principle store any kind of object, but should only be used to
 * store quaternions from the physics engine.
 * 
 * @author Modular Robots @ MMMI
 *
 */
public class PhysicsQuaternionHolder {
    /**
     * The quaternion being held 
     */
    private Object physicsQuaternion;
    /**
     * Create a physics engine independent quaternion holder
     * @param physicsQuaternion the quaternion to hold
     */
    public PhysicsQuaternionHolder(Object physicsQuaternion) {
        this.physicsQuaternion = physicsQuaternion;
    }
    /**
     * Get the physics engine specific quaternion stored in this holder
     * @return the quaternion being held
     */
    public Object get() { return physicsQuaternion; }
}
