/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ussr_samples_ATRONSampleController1 */

#ifndef _Included_ussr_samples_ATRONSampleController1
#define _Included_ussr_samples_ATRONSampleController1
#ifdef __cplusplus
extern "C" {
#endif
#undef ussr_samples_ATRONSampleController1_USE_NATIVE
#define ussr_samples_ATRONSampleController1_USE_NATIVE 1L
/*
 * Class:     ussr_samples_ATRONSampleController1
 * Method:    nativeActivate
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ussr_samples_ATRONSampleController1_nativeActivate
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
