/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version: 1.3.20
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.odejava.ode;


public class dContactGeom {
    private long swigCPtr;
    protected boolean swigCMemOwn;

    public dContactGeom( long cPtr, boolean cMemoryOwn ) {
        swigCMemOwn = cMemoryOwn;
        swigCPtr = cPtr;
    }

    protected void finalize() {
        delete();
    }

    public void delete() {
        if ( swigCPtr != 0 && swigCMemOwn ) {
            swigCMemOwn = false;
            OdeJNI.delete_dContactGeom( swigCPtr );
        }
        swigCPtr = 0;
    }

    public static long getCPtr( dContactGeom obj ) {
        return ( obj == null ) ? 0 : obj.swigCPtr;
    }

    public long getSwigCPtr() {
        return swigCPtr;
    }

    public void setSwigCPtr( long swigCPtr ) {
        this.swigCPtr = swigCPtr;
    }

    public void setPos( SWIGTYPE_p_float pos ) {
        OdeJNI.set_dContactGeom_pos( swigCPtr, SWIGTYPE_p_float.getCPtr( pos ) );
    }

    public SWIGTYPE_p_float getPos() {
        long cPtr = OdeJNI.get_dContactGeom_pos( swigCPtr );
        return ( cPtr == 0 ) ? null : new SWIGTYPE_p_float( cPtr, false );
    }

    public void setNormal( SWIGTYPE_p_float normal ) {
        OdeJNI.set_dContactGeom_normal( swigCPtr, SWIGTYPE_p_float.getCPtr( normal ) );
    }

    public SWIGTYPE_p_float getNormal() {
        long cPtr = OdeJNI.get_dContactGeom_normal( swigCPtr );
        return ( cPtr == 0 ) ? null : new SWIGTYPE_p_float( cPtr, false );
    }

    public void setDepth( float depth ) {
        OdeJNI.set_dContactGeom_depth( swigCPtr, depth );
    }

    public float getDepth() {
        return OdeJNI.get_dContactGeom_depth( swigCPtr );
    }

    public void setG1( SWIGTYPE_p_dGeomID g1 ) {
        OdeJNI.set_dContactGeom_g1( swigCPtr, SWIGTYPE_p_dGeomID.getCPtr( g1 ) );
    }

    public SWIGTYPE_p_dGeomID getG1() {
        return new SWIGTYPE_p_dGeomID( OdeJNI.get_dContactGeom_g1( swigCPtr ), true );
    }

    public void setG2( SWIGTYPE_p_dGeomID g2 ) {
        OdeJNI.set_dContactGeom_g2( swigCPtr, SWIGTYPE_p_dGeomID.getCPtr( g2 ) );
    }

    public SWIGTYPE_p_dGeomID getG2() {
        return new SWIGTYPE_p_dGeomID( OdeJNI.get_dContactGeom_g2( swigCPtr ), true );
    }

    public dContactGeom() {
        this( OdeJNI.new_dContactGeom(), true );
    }

}
