/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version: 1.3.20
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.odejava.ode;


public class dJointFeedback {
    private long swigCPtr;
    protected boolean swigCMemOwn;

    public dJointFeedback( long cPtr, boolean cMemoryOwn ) {
        swigCMemOwn = cMemoryOwn;
        swigCPtr = cPtr;
    }

    protected void finalize() {
        delete();
    }

    public void delete() {
        if ( swigCPtr != 0 && swigCMemOwn ) {
            swigCMemOwn = false;
            OdeJNI.delete_dJointFeedback( swigCPtr );
        }
        swigCPtr = 0;
    }

    public static long getCPtr( dJointFeedback obj ) {
        return ( obj == null ) ? 0 : obj.swigCPtr;
    }

    public long getSwigCPtr() {
        return swigCPtr;
    }

    public void setSwigCPtr( long swigCPtr ) {
        this.swigCPtr = swigCPtr;
    }

    public void setF1( SWIGTYPE_p_float f1 ) {
        OdeJNI.set_dJointFeedback_f1( swigCPtr, SWIGTYPE_p_float.getCPtr( f1 ) );
    }

    public SWIGTYPE_p_float getF1() {
        long cPtr = OdeJNI.get_dJointFeedback_f1( swigCPtr );
        return ( cPtr == 0 ) ? null : new SWIGTYPE_p_float( cPtr, false );
    }

    public void setT1( SWIGTYPE_p_float t1 ) {
        OdeJNI.set_dJointFeedback_t1( swigCPtr, SWIGTYPE_p_float.getCPtr( t1 ) );
    }

    public SWIGTYPE_p_float getT1() {
        long cPtr = OdeJNI.get_dJointFeedback_t1( swigCPtr );
        return ( cPtr == 0 ) ? null : new SWIGTYPE_p_float( cPtr, false );
    }

    public void setF2( SWIGTYPE_p_float f2 ) {
        OdeJNI.set_dJointFeedback_f2( swigCPtr, SWIGTYPE_p_float.getCPtr( f2 ) );
    }

    public SWIGTYPE_p_float getF2() {
        long cPtr = OdeJNI.get_dJointFeedback_f2( swigCPtr );
        return ( cPtr == 0 ) ? null : new SWIGTYPE_p_float( cPtr, false );
    }

    public void setT2( SWIGTYPE_p_float t2 ) {
        OdeJNI.set_dJointFeedback_t2( swigCPtr, SWIGTYPE_p_float.getCPtr( t2 ) );
    }

    public SWIGTYPE_p_float getT2() {
        long cPtr = OdeJNI.get_dJointFeedback_t2( swigCPtr );
        return ( cPtr == 0 ) ? null : new SWIGTYPE_p_float( cPtr, false );
    }

    public dJointFeedback() {
        this( OdeJNI.new_dJointFeedback(), true );
    }

}
