/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version: 1.3.20
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.odejava.ode;


public class dMass {
    private long swigCPtr;
    protected boolean swigCMemOwn;

    public dMass( long cPtr, boolean cMemoryOwn ) {
        swigCMemOwn = cMemoryOwn;
        swigCPtr = cPtr;
    }

    protected void finalize() {
        delete();
    }

    public void delete() {
        if ( swigCPtr != 0 && swigCMemOwn ) {
            swigCMemOwn = false;
            OdeJNI.delete_dMass( swigCPtr );
        }
        swigCPtr = 0;
    }

    public static long getCPtr( dMass obj ) {
        return ( obj == null ) ? 0 : obj.swigCPtr;
    }

    public long getSwigCPtr() {
        return swigCPtr;
    }

    public void setSwigCPtr( long swigCPtr ) {
        this.swigCPtr = swigCPtr;
    }

    public void setMass( float mass ) {
        OdeJNI.set_dMass_mass( swigCPtr, mass );
    }

    public float getMass() {
        return OdeJNI.get_dMass_mass( swigCPtr );
    }

    public void setC( SWIGTYPE_p_float c ) {
        OdeJNI.set_dMass_c( swigCPtr, SWIGTYPE_p_float.getCPtr( c ) );
    }

    public SWIGTYPE_p_float getC() {
        long cPtr = OdeJNI.get_dMass_c( swigCPtr );
        return ( cPtr == 0 ) ? null : new SWIGTYPE_p_float( cPtr, false );
    }

    public void setI( SWIGTYPE_p_float I ) {
        OdeJNI.set_dMass_I( swigCPtr, SWIGTYPE_p_float.getCPtr( I ) );
    }

    public SWIGTYPE_p_float getI() {
        long cPtr = OdeJNI.get_dMass_I( swigCPtr );
        return ( cPtr == 0 ) ? null : new SWIGTYPE_p_float( cPtr, false );
    }

    public SWIGTYPE_p_dMass getCPtr() {
        long cPtr = OdeJNI.dMass_getCPtr( swigCPtr );
        return ( cPtr == 0 ) ? null : new SWIGTYPE_p_dMass( cPtr, false );
    }

    public dMass() {
        this( OdeJNI.new_dMass(), true );
    }

}
