/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version: 1.3.20
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.odejava.ode;


public class dSurfaceParameters {
    private long swigCPtr;
    protected boolean swigCMemOwn;

    public dSurfaceParameters( long cPtr, boolean cMemoryOwn ) {
        swigCMemOwn = cMemoryOwn;
        swigCPtr = cPtr;
    }

    protected void finalize() {
        delete();
    }

    public void delete() {
        if ( swigCPtr != 0 && swigCMemOwn ) {
            swigCMemOwn = false;
            OdeJNI.delete_dSurfaceParameters( swigCPtr );
        }
        swigCPtr = 0;
    }

    public static long getCPtr( dSurfaceParameters obj ) {
        return ( obj == null ) ? 0 : obj.swigCPtr;
    }

    public long getSwigCPtr() {
        return swigCPtr;
    }

    public void setSwigCPtr( long swigCPtr ) {
        this.swigCPtr = swigCPtr;
    }

    public void setMode( int mode ) {
        OdeJNI.set_dSurfaceParameters_mode( swigCPtr, mode );
    }

    public int getMode() {
        return OdeJNI.get_dSurfaceParameters_mode( swigCPtr );
    }

    public void setMu( float mu ) {
        OdeJNI.set_dSurfaceParameters_mu( swigCPtr, mu );
    }

    public float getMu() {
        return OdeJNI.get_dSurfaceParameters_mu( swigCPtr );
    }

    public void setMu2( float mu2 ) {
        OdeJNI.set_dSurfaceParameters_mu2( swigCPtr, mu2 );
    }

    public float getMu2() {
        return OdeJNI.get_dSurfaceParameters_mu2( swigCPtr );
    }

    public void setBounce( float bounce ) {
        OdeJNI.set_dSurfaceParameters_bounce( swigCPtr, bounce );
    }

    public float getBounce() {
        return OdeJNI.get_dSurfaceParameters_bounce( swigCPtr );
    }

    public void setBounce_vel( float bounce_vel ) {
        OdeJNI.set_dSurfaceParameters_bounce_vel( swigCPtr, bounce_vel );
    }

    public float getBounce_vel() {
        return OdeJNI.get_dSurfaceParameters_bounce_vel( swigCPtr );
    }

    public void setSoft_erp( float soft_erp ) {
        OdeJNI.set_dSurfaceParameters_soft_erp( swigCPtr, soft_erp );
    }

    public float getSoft_erp() {
        return OdeJNI.get_dSurfaceParameters_soft_erp( swigCPtr );
    }

    public void setSoft_cfm( float soft_cfm ) {
        OdeJNI.set_dSurfaceParameters_soft_cfm( swigCPtr, soft_cfm );
    }

    public float getSoft_cfm() {
        return OdeJNI.get_dSurfaceParameters_soft_cfm( swigCPtr );
    }

    public void setMotion1( float motion1 ) {
        OdeJNI.set_dSurfaceParameters_motion1( swigCPtr, motion1 );
    }

    public float getMotion1() {
        return OdeJNI.get_dSurfaceParameters_motion1( swigCPtr );
    }

    public void setMotion2( float motion2 ) {
        OdeJNI.set_dSurfaceParameters_motion2( swigCPtr, motion2 );
    }

    public float getMotion2() {
        return OdeJNI.get_dSurfaceParameters_motion2( swigCPtr );
    }

    public void setSlip1( float slip1 ) {
        OdeJNI.set_dSurfaceParameters_slip1( swigCPtr, slip1 );
    }

    public float getSlip1() {
        return OdeJNI.get_dSurfaceParameters_slip1( swigCPtr );
    }

    public void setSlip2( float slip2 ) {
        OdeJNI.set_dSurfaceParameters_slip2( swigCPtr, slip2 );
    }

    public float getSlip2() {
        return OdeJNI.get_dSurfaceParameters_slip2( swigCPtr );
    }

    public dSurfaceParameters() {
        this( OdeJNI.new_dSurfaceParameters(), true );
    }

}
