package org.odejava.ode;

/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version: 1.3.20
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public interface OdeConstants {
    // enums and constants
    public final static String ODEJAVA_VERSION = OdeJNI.get_ODEJAVA_VERSION();
    public final static int dMaxUserClasses = OdeJNI.get_dMaxUserClasses();
    public final static int dSphereClass = OdeJNI.get_dSphereClass();
    public final static int dBoxClass = OdeJNI.get_dBoxClass();
    public final static int dCapsuleClass = OdeJNI.get_dCapsuleClass();
    public final static int dCylinderClass = OdeJNI.get_dCylinderClass();
    public final static int dPlaneClass = OdeJNI.get_dPlaneClass();
    public final static int dRayClass = OdeJNI.get_dRayClass();
    public final static int dGeomTransformClass = OdeJNI.get_dGeomTransformClass();
    public final static int dTriMeshClass = OdeJNI.get_dTriMeshClass();
    public final static int dFirstSpaceClass = OdeJNI.get_dFirstSpaceClass();
    public final static int dSimpleSpaceClass = OdeJNI.get_dSimpleSpaceClass();
    public final static int dHashSpaceClass = OdeJNI.get_dHashSpaceClass();
    public final static int dQuadTreeSpaceClass = OdeJNI.get_dQuadTreeSpaceClass();
    public final static int dLastSpaceClass = OdeJNI.get_dLastSpaceClass();
    public final static int dFirstUserClass = OdeJNI.get_dFirstUserClass();
    public final static int dLastUserClass = OdeJNI.get_dLastUserClass();
    public final static int dGeomNumClasses = OdeJNI.get_dGeomNumClasses();
    public final static int TRIMESH_FACE_NORMALS = OdeJNI.get_TRIMESH_FACE_NORMALS();
    public final static int TRIMESH_LAST_TRANSFORMATION = OdeJNI.get_TRIMESH_LAST_TRANSFORMATION();
    public final static int dJointTypeNone = OdeJNI.get_dJointTypeNone();
    public final static int dJointTypeBall = OdeJNI.get_dJointTypeBall();
    public final static int dJointTypeHinge = OdeJNI.get_dJointTypeHinge();
    public final static int dJointTypeSlider = OdeJNI.get_dJointTypeSlider();
    public final static int dJointTypeContact = OdeJNI.get_dJointTypeContact();
    public final static int dJointTypeUniversal = OdeJNI.get_dJointTypeUniversal();
    public final static int dJointTypeHinge2 = OdeJNI.get_dJointTypeHinge2();
    public final static int dJointTypeFixed = OdeJNI.get_dJointTypeFixed();
    public final static int dJointTypeNull = OdeJNI.get_dJointTypeNull();
    public final static int dJointTypeAMotor = OdeJNI.get_dJointTypeAMotor();
    public final static int dParamLoStop = OdeJNI.get_dParamLoStop();
    public final static int dParamHiStop = OdeJNI.get_dParamHiStop();
    public final static int dParamVel = OdeJNI.get_dParamVel();
    public final static int dParamFMax = OdeJNI.get_dParamFMax();
    public final static int dParamFudgeFactor = OdeJNI.get_dParamFudgeFactor();
    public final static int dParamBounce = OdeJNI.get_dParamBounce();
    public final static int dParamCFM = OdeJNI.get_dParamCFM();
    public final static int dParamStopERP = OdeJNI.get_dParamStopERP();
    public final static int dParamStopCFM = OdeJNI.get_dParamStopCFM();
    public final static int dParamSuspensionERP = OdeJNI.get_dParamSuspensionERP();
    public final static int dParamSuspensionCFM = OdeJNI.get_dParamSuspensionCFM();
    public final static int dParamERP = OdeJNI.get_dParamERP();
    public final static int dParamLoStop2 = OdeJNI.get_dParamLoStop2();
    public final static int dParamHiStop2 = OdeJNI.get_dParamHiStop2();
    public final static int dParamVel2 = OdeJNI.get_dParamVel2();
    public final static int dParamFMax2 = OdeJNI.get_dParamFMax2();
    public final static int dParamFudgeFactor2 = OdeJNI.get_dParamFudgeFactor2();
    public final static int dParamBounce2 = OdeJNI.get_dParamBounce2();
    public final static int dParamCFM2 = OdeJNI.get_dParamCFM2();
    public final static int dParamStopERP2 = OdeJNI.get_dParamStopERP2();
    public final static int dParamStopCFM2 = OdeJNI.get_dParamStopCFM2();
    public final static int dParamSuspensionERP2 = OdeJNI.get_dParamSuspensionERP2();
    public final static int dParamSuspensionCFM2 = OdeJNI.get_dParamSuspensionCFM2();
    public final static int dParamERP2 = OdeJNI.get_dParamERP2();
    public final static int dParamLoStop3 = OdeJNI.get_dParamLoStop3();
    public final static int dParamHiStop3 = OdeJNI.get_dParamHiStop3();
    public final static int dParamVel3 = OdeJNI.get_dParamVel3();
    public final static int dParamFMax3 = OdeJNI.get_dParamFMax3();
    public final static int dParamFudgeFactor3 = OdeJNI.get_dParamFudgeFactor3();
    public final static int dParamBounce3 = OdeJNI.get_dParamBounce3();
    public final static int dParamCFM3 = OdeJNI.get_dParamCFM3();
    public final static int dParamStopERP3 = OdeJNI.get_dParamStopERP3();
    public final static int dParamStopCFM3 = OdeJNI.get_dParamStopCFM3();
    public final static int dParamSuspensionERP3 = OdeJNI.get_dParamSuspensionERP3();
    public final static int dParamSuspensionCFM3 = OdeJNI.get_dParamSuspensionCFM3();
    public final static int dParamERP3 = OdeJNI.get_dParamERP3();
    public final static int dAMotorUser = OdeJNI.get_dAMotorUser();
    public final static int dAMotorEuler = OdeJNI.get_dAMotorEuler();
    public final static int dContactMu2 = OdeJNI.get_dContactMu2();
    public final static int dContactFDir1 = OdeJNI.get_dContactFDir1();
    public final static int dContactBounce = OdeJNI.get_dContactBounce();
    public final static int dContactSoftERP = OdeJNI.get_dContactSoftERP();
    public final static int dContactSoftCFM = OdeJNI.get_dContactSoftCFM();
    public final static int dContactMotion1 = OdeJNI.get_dContactMotion1();
    public final static int dContactMotion2 = OdeJNI.get_dContactMotion2();
    public final static int dContactSlip1 = OdeJNI.get_dContactSlip1();
    public final static int dContactSlip2 = OdeJNI.get_dContactSlip2();
    public final static int dContactApprox0 = OdeJNI.get_dContactApprox0();
    public final static int dContactApprox1_1 = OdeJNI.get_dContactApprox1_1();
    public final static int dContactApprox1_2 = OdeJNI.get_dContactApprox1_2();
    public final static int dContactApprox1 = OdeJNI.get_dContactApprox1();
}
