package org.odejava.ode;

/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version: 1.3.20
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


class OdeJNI {
    public final static native long new_floatArray( int jarg1 );

    public final static native void delete_floatArray( long jarg1 );

    public final static native float floatArray_getitem( long jarg1, int jarg2 );

    public final static native void floatArray_setitem( long jarg1, int jarg2, float jarg3 );

    public final static native long new_intArray( int jarg1 );

    public final static native void delete_intArray( long jarg1 );

    public final static native int intArray_getitem( long jarg1, int jarg2 );

    public final static native void intArray_setitem( long jarg1, int jarg2, int jarg3 );

    public final static native long new_geomIDArray( int jarg1 );

    public final static native void delete_geomIDArray( long jarg1 );

    public final static native long geomIDArray_getitem( long jarg1, int jarg2 );

    public final static native void geomIDArray_setitem( long jarg1, int jarg2, long jarg3 );

    public final static native String get_ODEJAVA_VERSION();

    public final static native long get_BODYID_ZERO();

    public final static native long get_JOINTGROUPID_ZERO();

    public final static native long get_PARENTSPACEID_ZERO();

    public final static native void setWorldID( long jarg1 );

    public final static native void setContactGroupID( long jarg1 );

    public final static native void setSurfaceMode( int jarg1 );

    public final static native void setSurfaceMu( float jarg1 );

    public final static native void setSurfaceMu2( float jarg1 );

    public final static native void setSurfaceBounce( float jarg1 );

    public final static native void setSurfaceBounceVel( float jarg1 );

    public final static native void setSurfaceMotion1( float jarg1 );

    public final static native void setSurfaceMotion2( float jarg1 );

    public final static native void setSurfaceSlip1( float jarg1 );

    public final static native void setSurfaceSlip2( float jarg1 );

    public final static native void setSurfaceSoftErp( float jarg1 );

    public final static native void setSurfaceSoftCfm( float jarg1 );

    public final static native void dGeomDestroy( long jarg1 );

    public final static native void dGeomSetData( long jarg1, long jarg2 );

    public final static native long dGeomGetData( long jarg1 );

    public final static native void dGeomSetBody( long jarg1, long jarg2 );

    public final static native long dGeomGetBody( long jarg1 );

    public final static native void dGeomSetPosition( long jarg1, float jarg2, float jarg3, float jarg4 );

    public final static native void dGeomSetRotation( long jarg1, long jarg2 );

    public final static native void dGeomSetQuaternion( long jarg1, long jarg2 );

    public final static native long dGeomGetPosition( long jarg1 );

    public final static native long dGeomGetRotation( long jarg1 );

    public final static native void dGeomGetQuaternion( long jarg1, long jarg2 );

    public final static native void dGeomGetAABB( long jarg1, long jarg2 );

    public final static native int dGeomIsSpace( long jarg1 );

    public final static native long dGeomGetSpace( long jarg1 );

    public final static native int dGeomGetClass( long jarg1 );

    public final static native void dGeomSetCategoryBits( long jarg1, long jarg2 );

    public final static native void dGeomSetCollideBits( long jarg1, long jarg2 );

    public final static native long dGeomGetCategoryBits( long jarg1 );

    public final static native long dGeomGetCollideBits( long jarg1 );

    public final static native void dGeomEnable( long jarg1 );

    public final static native void dGeomDisable( long jarg1 );

    public final static native int dGeomIsEnabled( long jarg1 );

    public final static native int dCollide( long jarg1, long jarg2, int jarg3, long jarg4, int jarg5 );

    public final static native void dSpaceCollide( long jarg1, long jarg2, long jarg3 );

    public final static native int get_dMaxUserClasses();

    public final static native int get_dSphereClass();

    public final static native int get_dBoxClass();

    public final static native int get_dCapsuleClass();

    public final static native int get_dCylinderClass();

    public final static native int get_dPlaneClass();

    public final static native int get_dRayClass();

    public final static native int get_dGeomTransformClass();

    public final static native int get_dTriMeshClass();

    public final static native int get_dFirstSpaceClass();

    public final static native int get_dSimpleSpaceClass();

    public final static native int get_dHashSpaceClass();

    public final static native int get_dQuadTreeSpaceClass();

    public final static native int get_dLastSpaceClass();

    public final static native int get_dFirstUserClass();

    public final static native int get_dLastUserClass();

    public final static native int get_dGeomNumClasses();

    public final static native long dCreateSphere( long jarg1, float jarg2 );

    public final static native void dGeomSphereSetRadius( long jarg1, float jarg2 );

    public final static native float dGeomSphereGetRadius( long jarg1 );

    public final static native float dGeomSpherePointDepth( long jarg1, float jarg2, float jarg3, float jarg4 );

    public final static native long dCreateBox( long jarg1, float jarg2, float jarg3, float jarg4 );

    public final static native void dGeomBoxSetLengths( long jarg1, float jarg2, float jarg3, float jarg4 );

    public final static native void dGeomBoxGetLengths( long jarg1, long jarg2 );

    public final static native float dGeomBoxPointDepth( long jarg1, float jarg2, float jarg3, float jarg4 );

    public final static native long dCreatePlane( long jarg1, float jarg2, float jarg3, float jarg4, float jarg5 );

    public final static native void dGeomPlaneSetParams( long jarg1, float jarg2, float jarg3, float jarg4, float jarg5 );

    public final static native void dGeomPlaneGetParams( long jarg1, long jarg2 );

    public final static native float dGeomPlanePointDepth( long jarg1, float jarg2, float jarg3, float jarg4 );

    public final static native long dCreateCapsule( long jarg1, float jarg2, float jarg3 );

    public final static native void dGeomCapsuleSetParams( long jarg1, float jarg2, float jarg3 );

    public final static native void dGeomCapsuleGetParams( long jarg1, long jarg2, long jarg3 );

    public final static native float dGeomCapsulePointDepth( long jarg1, float jarg2, float jarg3, float jarg4 );

    public final static native long dCreateRay( long jarg1, float jarg2 );

    public final static native void dGeomRaySetLength( long jarg1, float jarg2 );

    public final static native float dGeomRayGetLength( long jarg1 );

    public final static native void dGeomRaySet( long jarg1, float jarg2, float jarg3, float jarg4, float jarg5, float jarg6, float jarg7 );

    public final static native void dGeomRayGet( long jarg1, long jarg2, long jarg3 );

    public final static native void dGeomRaySetParams( long jarg1, int jarg2, int jarg3 );

    public final static native void dGeomRayGetParams( long jarg1, long jarg2, long jarg3 );

    public final static native long dCreateGeomTransform( long jarg1 );

    public final static native void dGeomTransformSetGeom( long jarg1, long jarg2 );

    public final static native long dGeomTransformGetGeom( long jarg1 );

    public final static native void dGeomTransformSetCleanup( long jarg1, int jarg2 );

    public final static native int dGeomTransformGetCleanup( long jarg1 );

    public final static native void dGeomTransformSetInfo( long jarg1, int jarg2 );

    public final static native int dGeomTransformGetInfo( long jarg1 );

    public final static native void dClosestLineSegmentPoints( long jarg1, long jarg2, long jarg3, long jarg4, long jarg5, long jarg6 );

    public final static native int dBoxTouchesBox( long jarg1, long jarg2, long jarg3, long jarg4, long jarg5, long jarg6 );

    public final static native void dInfiniteAABB( long jarg1, long jarg2 );

    public final static native void dCloseODE();

    public final static native void set_dGeomClass_bytes( long jarg1, int jarg2 );

    public final static native int get_dGeomClass_bytes( long jarg1 );

    public final static native void set_dGeomClass_collider( long jarg1, long jarg2 );

    public final static native long get_dGeomClass_collider( long jarg1 );

    public final static native void set_dGeomClass_aabb( long jarg1, long jarg2 );

    public final static native long get_dGeomClass_aabb( long jarg1 );

    public final static native void set_dGeomClass_aabb_test( long jarg1, long jarg2 );

    public final static native long get_dGeomClass_aabb_test( long jarg1 );

    public final static native void set_dGeomClass_dtor( long jarg1, long jarg2 );

    public final static native long get_dGeomClass_dtor( long jarg1 );

    public final static native long new_dGeomClass();

    public final static native void delete_dGeomClass( long jarg1 );

    public final static native int dCreateGeomClass( long jarg1 );

    public final static native long dGeomGetClassData( long jarg1 );

    public final static native long dCreateGeom( int jarg1 );

    public final static native long dSimpleSpaceCreate( long jarg1 );

    public final static native long dHashSpaceCreate( long jarg1 );

    public final static native long dQuadTreeSpaceCreate( long jarg1, long jarg2, long jarg3, int jarg4 );

    public final static native void dSpaceDestroy( long jarg1 );

    public final static native void dHashSpaceSetLevels( long jarg1, int jarg2, int jarg3 );

    public final static native void dSpaceSetCleanup( long jarg1, int jarg2 );

    public final static native int dSpaceGetCleanup( long jarg1 );

    public final static native void dSpaceAdd( long jarg1, long jarg2 );

    public final static native void dSpaceRemove( long jarg1, long jarg2 );

    public final static native int dSpaceQuery( long jarg1, long jarg2 );

    public final static native int dSpaceGetNumGeoms( long jarg1 );

    public final static native long dSpaceGetGeom( long jarg1, int jarg2 );

    public final static native long dGeomTriMeshDataCreate();

    public final static native void dGeomTriMeshDataDestroy( long jarg1 );

    public final static native int get_TRIMESH_FACE_NORMALS();

    public final static native int get_TRIMESH_LAST_TRANSFORMATION();

    public final static native void dGeomTriMeshDataSet( long jarg1, int jarg2, long jarg3 );

    public final static native long dGeomTriMeshDataGet( long jarg1, int jarg2 );

    public final static native void dGeomTriMeshDataBuildSingle( long jarg1, long jarg2, int jarg3, int jarg4, long jarg5, int jarg6, int jarg7 );

    public final static native void dGeomTriMeshDataBuildSingle1( long jarg1, long jarg2, int jarg3, int jarg4, long jarg5, int jarg6, int jarg7, long jarg8 );

    public final static native void dGeomTriMeshDataBuildSimple( long jarg1, long jarg2, int jarg3, long jarg4, int jarg5 );

    public final static native void dGeomTriMeshDataBuildSimple1( long jarg1, long jarg2, int jarg3, long jarg4, int jarg5, long jarg6 );

    public final static native long dCreateTriMesh( long jarg1, long jarg2, long jarg3, long jarg4, long jarg5 );

    public final static native void dGeomTriMeshSetData( long jarg1, long jarg2 );

    public final static native void dGeomTriMeshEnableTC( long jarg1, int jarg2, int jarg3 );

    public final static native int dGeomTriMeshIsTCEnabled( long jarg1, int jarg2 );

    public final static native void dGeomTriMeshClearTCCache( long jarg1 );

    public final static native void dGeomTriMeshGetTriangle( long jarg1, int jarg2, long jarg3, long jarg4, long jarg5 );

    public final static native void dGeomTriMeshGetPoint( long jarg1, int jarg2, float jarg3, float jarg4, long jarg5 );

    public final static native int get_dJointTypeNone();

    public final static native int get_dJointTypeBall();

    public final static native int get_dJointTypeHinge();

    public final static native int get_dJointTypeSlider();

    public final static native int get_dJointTypeContact();

    public final static native int get_dJointTypeUniversal();

    public final static native int get_dJointTypeHinge2();

    public final static native int get_dJointTypeFixed();

    public final static native int get_dJointTypeNull();

    public final static native int get_dJointTypeAMotor();

    public final static native int get_dParamLoStop();

    public final static native int get_dParamHiStop();

    public final static native int get_dParamVel();

    public final static native int get_dParamFMax();

    public final static native int get_dParamFudgeFactor();

    public final static native int get_dParamBounce();

    public final static native int get_dParamCFM();

    public final static native int get_dParamStopERP();

    public final static native int get_dParamStopCFM();

    public final static native int get_dParamSuspensionERP();

    public final static native int get_dParamSuspensionCFM();

    public final static native int get_dParamERP();

    public final static native int get_dParamLoStop2();

    public final static native int get_dParamHiStop2();

    public final static native int get_dParamVel2();

    public final static native int get_dParamFMax2();

    public final static native int get_dParamFudgeFactor2();

    public final static native int get_dParamBounce2();

    public final static native int get_dParamCFM2();

    public final static native int get_dParamStopERP2();

    public final static native int get_dParamStopCFM2();

    public final static native int get_dParamSuspensionERP2();

    public final static native int get_dParamSuspensionCFM2();

    public final static native int get_dParamERP2();

    public final static native int get_dParamLoStop3();

    public final static native int get_dParamHiStop3();

    public final static native int get_dParamVel3();

    public final static native int get_dParamFMax3();

    public final static native int get_dParamFudgeFactor3();

    public final static native int get_dParamBounce3();

    public final static native int get_dParamCFM3();

    public final static native int get_dParamStopERP3();

    public final static native int get_dParamStopCFM3();

    public final static native int get_dParamSuspensionERP3();

    public final static native int get_dParamSuspensionCFM3();

    public final static native int get_dParamERP3();

    public final static native int get_dAMotorUser();

    public final static native int get_dAMotorEuler();

    public final static native void set_dJointFeedback_f1( long jarg1, long jarg2 );

    public final static native long get_dJointFeedback_f1( long jarg1 );

    public final static native void set_dJointFeedback_t1( long jarg1, long jarg2 );

    public final static native long get_dJointFeedback_t1( long jarg1 );

    public final static native void set_dJointFeedback_f2( long jarg1, long jarg2 );

    public final static native long get_dJointFeedback_f2( long jarg1 );

    public final static native void set_dJointFeedback_t2( long jarg1, long jarg2 );

    public final static native long get_dJointFeedback_t2( long jarg1 );

    public final static native long new_dJointFeedback();

    public final static native void delete_dJointFeedback( long jarg1 );

    public final static native int get_dContactMu2();

    public final static native int get_dContactFDir1();

    public final static native int get_dContactBounce();

    public final static native int get_dContactSoftERP();

    public final static native int get_dContactSoftCFM();

    public final static native int get_dContactMotion1();

    public final static native int get_dContactMotion2();

    public final static native int get_dContactSlip1();

    public final static native int get_dContactSlip2();

    public final static native int get_dContactApprox0();

    public final static native int get_dContactApprox1_1();

    public final static native int get_dContactApprox1_2();

    public final static native int get_dContactApprox1();

    public final static native void set_dSurfaceParameters_mode( long jarg1, int jarg2 );

    public final static native int get_dSurfaceParameters_mode( long jarg1 );

    public final static native void set_dSurfaceParameters_mu( long jarg1, float jarg2 );

    public final static native float get_dSurfaceParameters_mu( long jarg1 );

    public final static native void set_dSurfaceParameters_mu2( long jarg1, float jarg2 );

    public final static native float get_dSurfaceParameters_mu2( long jarg1 );

    public final static native void set_dSurfaceParameters_bounce( long jarg1, float jarg2 );

    public final static native float get_dSurfaceParameters_bounce( long jarg1 );

    public final static native void set_dSurfaceParameters_bounce_vel( long jarg1, float jarg2 );

    public final static native float get_dSurfaceParameters_bounce_vel( long jarg1 );

    public final static native void set_dSurfaceParameters_soft_erp( long jarg1, float jarg2 );

    public final static native float get_dSurfaceParameters_soft_erp( long jarg1 );

    public final static native void set_dSurfaceParameters_soft_cfm( long jarg1, float jarg2 );

    public final static native float get_dSurfaceParameters_soft_cfm( long jarg1 );

    public final static native void set_dSurfaceParameters_motion1( long jarg1, float jarg2 );

    public final static native float get_dSurfaceParameters_motion1( long jarg1 );

    public final static native void set_dSurfaceParameters_motion2( long jarg1, float jarg2 );

    public final static native float get_dSurfaceParameters_motion2( long jarg1 );

    public final static native void set_dSurfaceParameters_slip1( long jarg1, float jarg2 );

    public final static native float get_dSurfaceParameters_slip1( long jarg1 );

    public final static native void set_dSurfaceParameters_slip2( long jarg1, float jarg2 );

    public final static native float get_dSurfaceParameters_slip2( long jarg1 );

    public final static native long new_dSurfaceParameters();

    public final static native void delete_dSurfaceParameters( long jarg1 );

    public final static native void set_dContactGeom_pos( long jarg1, long jarg2 );

    public final static native long get_dContactGeom_pos( long jarg1 );

    public final static native void set_dContactGeom_normal( long jarg1, long jarg2 );

    public final static native long get_dContactGeom_normal( long jarg1 );

    public final static native void set_dContactGeom_depth( long jarg1, float jarg2 );

    public final static native float get_dContactGeom_depth( long jarg1 );

    public final static native void set_dContactGeom_g1( long jarg1, long jarg2 );

    public final static native long get_dContactGeom_g1( long jarg1 );

    public final static native void set_dContactGeom_g2( long jarg1, long jarg2 );

    public final static native long get_dContactGeom_g2( long jarg1 );

    public final static native long new_dContactGeom();

    public final static native void delete_dContactGeom( long jarg1 );

    public final static native void set_dContact_surface( long jarg1, long jarg2 );

    public final static native long get_dContact_surface( long jarg1 );

    public final static native void set_dContact_geom( long jarg1, long jarg2 );

    public final static native long get_dContact_geom( long jarg1 );

    public final static native void set_dContact_fdir1( long jarg1, long jarg2 );

    public final static native long get_dContact_fdir1( long jarg1 );

    public final static native long new_dContact();

    public final static native void delete_dContact( long jarg1 );

    public final static native void dMassSetZero( long jarg1 );

    public final static native void dMassSetParameters( long jarg1, float jarg2, float jarg3, float jarg4, float jarg5, float jarg6, float jarg7, float jarg8, float jarg9, float jarg10, float jarg11 );

    public final static native void dMassSetSphere( long jarg1, float jarg2, float jarg3 );

    public final static native void dMassSetSphereTotal( long jarg1, float jarg2, float jarg3 );

    public final static native void dMassSetCapsule( long jarg1, float jarg2, int jarg3, float jarg4, float jarg5 );

    public final static native void dMassSetCapsuleTotal( long jarg1, float jarg2, int jarg3, float jarg4, float jarg5 );

    public final static native void dMassSetCylinder( long jarg1, float jarg2, int jarg3, float jarg4, float jarg5 );

    public final static native void dMassSetCylinderTotal( long jarg1, float jarg2, int jarg3, float jarg4, float jarg5 );

    public final static native void dMassSetBox( long jarg1, float jarg2, float jarg3, float jarg4, float jarg5 );

    public final static native void dMassSetBoxTotal( long jarg1, float jarg2, float jarg3, float jarg4, float jarg5 );

    public final static native void dMassAdjust( long jarg1, float jarg2 );

    public final static native void dMassTranslate( long jarg1, float jarg2, float jarg3, float jarg4 );

    public final static native void dMassRotate( long jarg1, long jarg2 );

    public final static native void dMassAdd( long jarg1, long jarg2 );

    public final static native void set_dMass_mass( long jarg1, float jarg2 );

    public final static native float get_dMass_mass( long jarg1 );

    public final static native void set_dMass_c( long jarg1, long jarg2 );

    public final static native long get_dMass_c( long jarg1 );

    public final static native void set_dMass_I( long jarg1, long jarg2 );

    public final static native long get_dMass_I( long jarg1 );

    public final static native long dMass_getCPtr( long jarg1 );

    public final static native long new_dMass();

    public final static native void delete_dMass( long jarg1 );

    public final static native long dWorldCreate();

    public final static native void dWorldDestroy( long jarg1 );

    public final static native void dWorldSetGravity( long jarg1, float jarg2, float jarg3, float jarg4 );

    public final static native void dWorldGetGravity( long jarg1, long jarg2 );

    public final static native void dWorldSetERP( long jarg1, float jarg2 );

    public final static native float dWorldGetERP( long jarg1 );

    public final static native void dWorldSetCFM( long jarg1, float jarg2 );

    public final static native float dWorldGetCFM( long jarg1 );

    public final static native void dWorldStep( long jarg1, float jarg2 );

    public final static native void dWorldImpulseToForce( long jarg1, float jarg2, float jarg3, float jarg4, float jarg5, long jarg6 );

    public final static native void dWorldSetAutoDisableFlag( long jarg1, int jarg2 );

    public final static native int dWorldGetAutoDisableFlag( long jarg1 );

    public final static native void dWorldSetAutoDisableLinearThreshold( long jarg1, float jarg2 );

    public final static native float dWorldGetAutoDisableLinearThreshold( long jarg1 );

    public final static native void dWorldSetAutoDisableAngularThreshold( long jarg1, float jarg2 );

    public final static native float dWorldGetAutoDisableAngularThreshold( long jarg1 );

    public final static native void dWorldSetAutoDisableSteps( long jarg1, int jarg2 );

    public final static native int dWorldGetAutoDisableSteps( long jarg1 );

    public final static native void dWorldSetAutoDisableTime( long jarg1, float jarg2 );

    public final static native float dWorldGetAutoDisableTime( long jarg1 );

    public final static native void dWorldSetContactMaxCorrectingVel( long jarg1, float jarg2 );

    public final static native float dWorldGetContactMaxCorrectingVel( long jarg1 );

    public final static native void dWorldSetContactSurfaceLayer( long jarg1, float jarg2 );

    public final static native float dWorldGetContactSurfaceLayer( long jarg1 );

    public final static native void dWorldStepFast1( long jarg1, float jarg2, int jarg3 );

    public final static native void dWorldSetAutoEnableDepthSF1( long jarg1, int jarg2 );

    public final static native int dWorldGetAutoEnableDepthSF1( long jarg1 );

    public final static native void dWorldQuickStep( long jarg1, float jarg2 );

    public final static native void dWorldSetQuickStepNumIterations( long jarg1, int jarg2 );

    public final static native int dWorldGetQuickStepNumIterations( long jarg1 );

    public final static native long dBodyCreate( long jarg1 );

    public final static native void dBodyDestroy( long jarg1 );

    public final static native void dBodySetData( long jarg1, long jarg2 );

    public final static native long dBodyGetData( long jarg1 );

    public final static native void dBodySetPosition( long jarg1, float jarg2, float jarg3, float jarg4 );

    public final static native void dBodySetRotation( long jarg1, long jarg2 );

    public final static native void dBodySetQuaternion( long jarg1, long jarg2 );

    public final static native void dBodySetLinearVel( long jarg1, float jarg2, float jarg3, float jarg4 );

    public final static native void dBodySetAngularVel( long jarg1, float jarg2, float jarg3, float jarg4 );

    public final static native long dBodyGetPosition( long jarg1 );

    public final static native long dBodyGetRotation( long jarg1 );

    public final static native long dBodyGetQuaternion( long jarg1 );

    public final static native long dBodyGetLinearVel( long jarg1 );

    public final static native long dBodyGetAngularVel( long jarg1 );

    public final static native void dBodySetMass( long jarg1, long jarg2 );

    public final static native void dBodyGetMass( long jarg1, long jarg2 );

    public final static native void dBodyAddForce( long jarg1, float jarg2, float jarg3, float jarg4 );

    public final static native void dBodyAddTorque( long jarg1, float jarg2, float jarg3, float jarg4 );

    public final static native void dBodyAddRelForce( long jarg1, float jarg2, float jarg3, float jarg4 );

    public final static native void dBodyAddRelTorque( long jarg1, float jarg2, float jarg3, float jarg4 );

    public final static native void dBodyAddForceAtPos( long jarg1, float jarg2, float jarg3, float jarg4, float jarg5, float jarg6, float jarg7 );

    public final static native void dBodyAddForceAtRelPos( long jarg1, float jarg2, float jarg3, float jarg4, float jarg5, float jarg6, float jarg7 );

    public final static native void dBodyAddRelForceAtPos( long jarg1, float jarg2, float jarg3, float jarg4, float jarg5, float jarg6, float jarg7 );

    public final static native void dBodyAddRelForceAtRelPos( long jarg1, float jarg2, float jarg3, float jarg4, float jarg5, float jarg6, float jarg7 );

    public final static native long dBodyGetForce( long jarg1 );

    public final static native long dBodyGetTorque( long jarg1 );

    public final static native void dBodySetForce( long jarg1, float jarg2, float jarg3, float jarg4 );

    public final static native void dBodySetTorque( long jarg1, float jarg2, float jarg3, float jarg4 );

    public final static native void dBodyGetRelPointPos( long jarg1, float jarg2, float jarg3, float jarg4, long jarg5 );

    public final static native void dBodyGetRelPointVel( long jarg1, float jarg2, float jarg3, float jarg4, long jarg5 );

    public final static native void dBodyGetPointVel( long jarg1, float jarg2, float jarg3, float jarg4, long jarg5 );

    public final static native void dBodyGetPosRelPoint( long jarg1, float jarg2, float jarg3, float jarg4, long jarg5 );

    public final static native void dBodyVectorToWorld( long jarg1, float jarg2, float jarg3, float jarg4, long jarg5 );

    public final static native void dBodyVectorFromWorld( long jarg1, float jarg2, float jarg3, float jarg4, long jarg5 );

    public final static native void dBodySetFiniteRotationMode( long jarg1, int jarg2 );

    public final static native void dBodySetFiniteRotationAxis( long jarg1, float jarg2, float jarg3, float jarg4 );

    public final static native int dBodyGetFiniteRotationMode( long jarg1 );

    public final static native void dBodyGetFiniteRotationAxis( long jarg1, long jarg2 );

    public final static native int dBodyGetNumJoints( long jarg1 );

    public final static native long dBodyGetJoint( long jarg1, int jarg2 );

    public final static native void dBodyEnable( long jarg1 );

    public final static native void dBodyDisable( long jarg1 );

    public final static native int dBodyIsEnabled( long jarg1 );

    public final static native void dBodySetGravityMode( long jarg1, int jarg2 );

    public final static native int dBodyGetGravityMode( long jarg1 );

    public final static native void dBodySetAutoDisableDefaults( long jarg1 );

    public final static native void dBodySetAutoDisableFlag( long jarg1, int jarg2 );

    public final static native int dBodyGetAutoDisableFlag( long jarg1 );

    public final static native void dBodySetAutoDisableLinearThreshold( long jarg1, float jarg2 );

    public final static native float dBodyGetAutoDisableLinearThreshold( long jarg1 );

    public final static native void dBodySetAutoDisableAngularThreshold( long jarg1, float jarg2 );

    public final static native float dBodyGetAutoDisableAngularThreshold( long jarg1 );

    public final static native void dBodySetAutoDisableSteps( long jarg1, int jarg2 );

    public final static native int dBodyGetAutoDisableSteps( long jarg1 );

    public final static native void dBodySetAutoDisableTime( long jarg1, float jarg2 );

    public final static native float dBodyGetAutoDisableTime( long jarg1 );

    public final static native long dJointCreateBall( long jarg1, long jarg2 );

    public final static native long dJointCreateHinge( long jarg1, long jarg2 );

    public final static native long dJointCreateSlider( long jarg1, long jarg2 );

    public final static native long dJointCreateContact( long jarg1, long jarg2, long jarg3 );

    public final static native long dJointCreateHinge2( long jarg1, long jarg2 );

    public final static native long dJointCreateUniversal( long jarg1, long jarg2 );

    public final static native long dJointCreateFixed( long jarg1, long jarg2 );

    public final static native long dJointCreateNull( long jarg1, long jarg2 );

    public final static native long dJointCreateAMotor( long jarg1, long jarg2 );

    public final static native void dJointDestroy( long jarg1 );

    public final static native long dJointGroupCreate( int jarg1 );

    public final static native void dJointGroupDestroy( long jarg1 );

    public final static native void dJointGroupEmpty( long jarg1 );

    public final static native void dJointAttach( long jarg1, long jarg2, long jarg3 );

    public final static native void dJointSetData( long jarg1, long jarg2 );

    public final static native long dJointGetData( long jarg1 );

    public final static native int dJointGetType( long jarg1 );

    public final static native long dJointGetBody( long jarg1, int jarg2 );

    public final static native void dJointSetFeedback( long jarg1, long jarg2 );

    public final static native long dJointGetFeedback( long jarg1 );

    public final static native void dJointSetBallAnchor( long jarg1, float jarg2, float jarg3, float jarg4 );

    public final static native void dJointSetBallParam( long jarg1, int jarg2, float jarg3 );

    public final static native float dJointGetBallParam( long jarg1, int jarg2 );

    public final static native void dJointSetHingeAnchor( long jarg1, float jarg2, float jarg3, float jarg4 );

    public final static native void dJointSetHingeAxis( long jarg1, float jarg2, float jarg3, float jarg4 );

    public final static native void dJointSetHingeParam( long jarg1, int jarg2, float jarg3 );

    public final static native void dJointSetSliderAxis( long jarg1, float jarg2, float jarg3, float jarg4 );

    public final static native void dJointSetSliderParam( long jarg1, int jarg2, float jarg3 );

    public final static native void dJointSetHinge2Anchor( long jarg1, float jarg2, float jarg3, float jarg4 );

    public final static native void dJointSetHinge2Axis1( long jarg1, float jarg2, float jarg3, float jarg4 );

    public final static native void dJointSetHinge2Axis2( long jarg1, float jarg2, float jarg3, float jarg4 );

    public final static native void dJointSetHinge2Param( long jarg1, int jarg2, float jarg3 );

    public final static native void dJointSetUniversalAnchor( long jarg1, float jarg2, float jarg3, float jarg4 );

    public final static native void dJointSetUniversalAxis1( long jarg1, float jarg2, float jarg3, float jarg4 );

    public final static native void dJointSetUniversalAxis2( long jarg1, float jarg2, float jarg3, float jarg4 );

    public final static native void dJointSetUniversalParam( long jarg1, int jarg2, float jarg3 );

    public final static native void dJointSetFixed( long jarg1 );

    public final static native void dJointSetFixedParam( long jarg1, int jarg2, float jarg3 );

    public final static native float dJointGetFixedParam( long jarg1, int jarg2 );

    public final static native void dJointSetAMotorNumAxes( long jarg1, int jarg2 );

    public final static native void dJointSetAMotorAxis( long jarg1, int jarg2, int jarg3, float jarg4, float jarg5, float jarg6 );

    public final static native void dJointSetAMotorAngle( long jarg1, int jarg2, float jarg3 );

    public final static native void dJointSetAMotorParam( long jarg1, int jarg2, float jarg3 );

    public final static native void dJointSetAMotorMode( long jarg1, int jarg2 );

    public final static native void dJointGetBallAnchor( long jarg1, long jarg2 );

    public final static native void dJointGetBallAnchor2( long jarg1, long jarg2 );

    public final static native void dJointGetHingeAnchor( long jarg1, long jarg2 );

    public final static native void dJointGetHingeAnchor2( long jarg1, long jarg2 );

    public final static native void dJointGetHingeAxis( long jarg1, long jarg2 );

    public final static native float dJointGetHingeParam( long jarg1, int jarg2 );

    public final static native float dJointGetHingeAngle( long jarg1 );

    public final static native float dJointGetHingeAngleRate( long jarg1 );

    public final static native float dJointGetSliderPosition( long jarg1 );

    public final static native float dJointGetSliderPositionRate( long jarg1 );

    public final static native void dJointGetSliderAxis( long jarg1, long jarg2 );

    public final static native float dJointGetSliderParam( long jarg1, int jarg2 );

    public final static native void dJointGetHinge2Anchor( long jarg1, long jarg2 );

    public final static native void dJointGetHinge2Anchor2( long jarg1, long jarg2 );

    public final static native void dJointGetHinge2Axis1( long jarg1, long jarg2 );

    public final static native void dJointGetHinge2Axis2( long jarg1, long jarg2 );

    public final static native float dJointGetHinge2Param( long jarg1, int jarg2 );

    public final static native float dJointGetHinge2Angle1( long jarg1 );

    public final static native float dJointGetHinge2Angle1Rate( long jarg1 );

    public final static native float dJointGetHinge2Angle2Rate( long jarg1 );

    public final static native void dJointGetUniversalAnchor( long jarg1, long jarg2 );

    public final static native void dJointGetUniversalAnchor2( long jarg1, long jarg2 );

    public final static native void dJointGetUniversalAxis1( long jarg1, long jarg2 );

    public final static native void dJointGetUniversalAxis2( long jarg1, long jarg2 );

    public final static native float dJointGetUniversalParam( long jarg1, int jarg2 );

    public final static native float dJointGetUniversalAngle1( long jarg1 );

    public final static native float dJointGetUniversalAngle2( long jarg1 );

    public final static native float dJointGetUniversalAngle1Rate( long jarg1 );

    public final static native float dJointGetUniversalAngle2Rate( long jarg1 );

    public final static native int dJointGetAMotorNumAxes( long jarg1 );

    public final static native void dJointGetAMotorAxis( long jarg1, int jarg2, long jarg3 );

    public final static native int dJointGetAMotorAxisRel( long jarg1, int jarg2 );

    public final static native float dJointGetAMotorAngle( long jarg1, int jarg2 );

    public final static native float dJointGetAMotorAngleRate( long jarg1, int jarg2 );

    public final static native float dJointGetAMotorParam( long jarg1, int jarg2 );

    public final static native int dJointGetAMotorMode( long jarg1 );

    public final static native int dAreConnected( long jarg1, long jarg2 );

    public final static native int dAreConnectedExcluding( long jarg1, long jarg2, int jarg3 );

    public final static native void dRandSetSeed( int jarg1 );

    public final static native void dRSetIdentity( long jarg1 );

    public final static native void dRFromAxisAndAngle( long jarg1, float jarg2, float jarg3, float jarg4, float jarg5 );

    public final static native void dRFromEulerAngles( long jarg1, float jarg2, float jarg3, float jarg4 );

    public final static native void dRFrom2Axes( long jarg1, float jarg2, float jarg3, float jarg4, float jarg5, float jarg6, float jarg7 );

    public final static native void dRFromZAxis( long jarg1, float jarg2, float jarg3, float jarg4 );

    public final static native void dQSetIdentity( long jarg1 );

    public final static native void dQFromAxisAndAngle( long jarg1, float jarg2, float jarg3, float jarg4, float jarg5 );

    public final static native void dQMultiply0( long jarg1, long jarg2, long jarg3 );

    public final static native void dQMultiply1( long jarg1, long jarg2, long jarg3 );

    public final static native void dQMultiply2( long jarg1, long jarg2, long jarg3 );

    public final static native void dQMultiply3( long jarg1, long jarg2, long jarg3 );

    public final static native void dQtoR( long jarg1, long jarg2 );

    public final static native void dRtoQ( long jarg1, long jarg2 );

    public final static native void dWtoDQ( long jarg1, long jarg2, long jarg3 );

    public final static native long dCreateCylinder( long jarg1, float jarg2, float jarg3 );

    public final static native void dGeomCylinderSetParams( long jarg1, float jarg2, float jarg3 );

    public final static native void dGeomCylinderGetParams( long jarg1, long jarg2, long jarg3 );
}
