/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version: 1.3.20
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.odejava.ode;


public class SWIGTYPE_p_dTriRayCallback {
    private long swigCPtr;

    public SWIGTYPE_p_dTriRayCallback( long cPtr, boolean bFutureUse ) {
        swigCPtr = cPtr;
    }

    protected SWIGTYPE_p_dTriRayCallback() {
        swigCPtr = 0;
    }

    public static long getCPtr( SWIGTYPE_p_dTriRayCallback obj ) {
        return ( obj == null ) ? 0 : obj.swigCPtr;
    }

    public long getSwigCPtr() {
        return swigCPtr;
    }

    public void setSwigCPtr( long swigCPtr ) {
        this.swigCPtr = swigCPtr;
    }
}

