/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version: 1.3.20
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.odejava.ode;


public class SWIGTYPE_p_dxJointContact {
    private long swigCPtr;

    protected SWIGTYPE_p_dxJointContact( long cPtr, boolean bFutureUse ) {
        swigCPtr = cPtr;
    }

    protected SWIGTYPE_p_dxJointContact() {
        swigCPtr = 0;
    }

    protected static long getCPtr( SWIGTYPE_p_dxJointContact obj ) {
        return ( obj == null ) ? 0 : obj.swigCPtr;
    }
}

