/* This file was generated by SableCC (http://www.sablecc.org/). */

package dcd.highlevel.rdcd.parser.node;

import java.util.*;
import dcd.highlevel.rdcd.parser.analysis.*;

@SuppressWarnings("nls")
public final class ADeploymentSpec extends PDeploymentSpec
{
    private TDeployment _deployment_;
    private TLBrace _lBrace_;
    private final LinkedList<TIdentifier> _identifier_ = new LinkedList<TIdentifier>();
    private TRBrace _rBrace_;

    public ADeploymentSpec()
    {
        // Constructor
    }

    public ADeploymentSpec(
        @SuppressWarnings("hiding") TDeployment _deployment_,
        @SuppressWarnings("hiding") TLBrace _lBrace_,
        @SuppressWarnings("hiding") List<TIdentifier> _identifier_,
        @SuppressWarnings("hiding") TRBrace _rBrace_)
    {
        // Constructor
        setDeployment(_deployment_);

        setLBrace(_lBrace_);

        setIdentifier(_identifier_);

        setRBrace(_rBrace_);

    }

    @Override
    public Object clone()
    {
        return new ADeploymentSpec(
            cloneNode(this._deployment_),
            cloneNode(this._lBrace_),
            cloneList(this._identifier_),
            cloneNode(this._rBrace_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADeploymentSpec(this);
    }

    public TDeployment getDeployment()
    {
        return this._deployment_;
    }

    public void setDeployment(TDeployment node)
    {
        if(this._deployment_ != null)
        {
            this._deployment_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._deployment_ = node;
    }

    public TLBrace getLBrace()
    {
        return this._lBrace_;
    }

    public void setLBrace(TLBrace node)
    {
        if(this._lBrace_ != null)
        {
            this._lBrace_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._lBrace_ = node;
    }

    public LinkedList<TIdentifier> getIdentifier()
    {
        return this._identifier_;
    }

    public void setIdentifier(List<TIdentifier> list)
    {
        this._identifier_.clear();
        this._identifier_.addAll(list);
        for(TIdentifier e : list)
        {
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
        }
    }

    public TRBrace getRBrace()
    {
        return this._rBrace_;
    }

    public void setRBrace(TRBrace node)
    {
        if(this._rBrace_ != null)
        {
            this._rBrace_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._rBrace_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._deployment_)
            + toString(this._lBrace_)
            + toString(this._identifier_)
            + toString(this._rBrace_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._deployment_ == child)
        {
            this._deployment_ = null;
            return;
        }

        if(this._lBrace_ == child)
        {
            this._lBrace_ = null;
            return;
        }

        if(this._identifier_.remove(child))
        {
            return;
        }

        if(this._rBrace_ == child)
        {
            this._rBrace_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._deployment_ == oldChild)
        {
            setDeployment((TDeployment) newChild);
            return;
        }

        if(this._lBrace_ == oldChild)
        {
            setLBrace((TLBrace) newChild);
            return;
        }

        for(ListIterator<TIdentifier> i = this._identifier_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((TIdentifier) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        if(this._rBrace_ == oldChild)
        {
            setRBrace((TRBrace) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
