/* This file was generated by SableCC (http://www.sablecc.org/). */

package dcd.highlevel.rdcd.parser.node;

import dcd.highlevel.rdcd.parser.analysis.*;

@SuppressWarnings("nls")
public final class AOctalIntegerLiteral extends PIntegerLiteral
{
    private TOctalIntegerLiteral _octalIntegerLiteral_;

    public AOctalIntegerLiteral()
    {
        // Constructor
    }

    public AOctalIntegerLiteral(
        @SuppressWarnings("hiding") TOctalIntegerLiteral _octalIntegerLiteral_)
    {
        // Constructor
        setOctalIntegerLiteral(_octalIntegerLiteral_);

    }

    @Override
    public Object clone()
    {
        return new AOctalIntegerLiteral(
            cloneNode(this._octalIntegerLiteral_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAOctalIntegerLiteral(this);
    }

    public TOctalIntegerLiteral getOctalIntegerLiteral()
    {
        return this._octalIntegerLiteral_;
    }

    public void setOctalIntegerLiteral(TOctalIntegerLiteral node)
    {
        if(this._octalIntegerLiteral_ != null)
        {
            this._octalIntegerLiteral_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._octalIntegerLiteral_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._octalIntegerLiteral_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._octalIntegerLiteral_ == child)
        {
            this._octalIntegerLiteral_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._octalIntegerLiteral_ == oldChild)
        {
            setOctalIntegerLiteral((TOctalIntegerLiteral) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
