/* This file was generated by SableCC (http://www.sablecc.org/). */

package dcd.highlevel.rdcd.parser.node;

import dcd.highlevel.rdcd.parser.analysis.*;

@SuppressWarnings("nls")
public final class ASimpleNameName extends PName
{
    private PSimpleName _simpleName_;

    public ASimpleNameName()
    {
        // Constructor
    }

    public ASimpleNameName(
        @SuppressWarnings("hiding") PSimpleName _simpleName_)
    {
        // Constructor
        setSimpleName(_simpleName_);

    }

    @Override
    public Object clone()
    {
        return new ASimpleNameName(
            cloneNode(this._simpleName_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASimpleNameName(this);
    }

    public PSimpleName getSimpleName()
    {
        return this._simpleName_;
    }

    public void setSimpleName(PSimpleName node)
    {
        if(this._simpleName_ != null)
        {
            this._simpleName_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._simpleName_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._simpleName_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._simpleName_ == child)
        {
            this._simpleName_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._simpleName_ == oldChild)
        {
            setSimpleName((PSimpleName) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
