/* This file was generated by SableCC (http://www.sablecc.org/). */

package dcd.highlevel.rdcd.parser.node;

import dcd.highlevel.rdcd.parser.analysis.*;

@SuppressWarnings("nls")
public final class TDeployment extends Token
{
    public TDeployment()
    {
        super.setText("deployment");
    }

    public TDeployment(int line, int pos)
    {
        super.setText("deployment");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TDeployment(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTDeployment(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TDeployment text.");
    }
}
