/* This file was generated by SableCC (http://www.sablecc.org/). */

package dcd.highlevel.rdcd.parser.node;

import dcd.highlevel.rdcd.parser.analysis.*;

@SuppressWarnings("nls")
public final class TModAssign extends Token
{
    public TModAssign()
    {
        super.setText("%=");
    }

    public TModAssign(int line, int pos)
    {
        super.setText("%=");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TModAssign(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTModAssign(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TModAssign text.");
    }
}
