/* This file was generated by SableCC (http://www.sablecc.org/). */

package dcd.highlevel.rdcd.parser.node;

import dcd.highlevel.rdcd.parser.analysis.*;

@SuppressWarnings("nls")
public final class TShiftLeftAssign extends Token
{
    public TShiftLeftAssign()
    {
        super.setText("<<=");
    }

    public TShiftLeftAssign(int line, int pos)
    {
        super.setText("<<=");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TShiftLeftAssign(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTShiftLeftAssign(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TShiftLeftAssign text.");
    }
}
